version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
      time: "01:00"
    labels:
      - scope:dependency
    target-branch: "main"
0x6D057d43fAeDA81d5a245e4F56C88e330bBeA406
